export const SET_COVER = 'SET_COVER';
export const GET_FIGHTERS_SUCCESS = 'GET_FIGHTERS_SUCCESS';
export const GET_FIGHTERS_LOADING = 'GET_FIGHTERS_LOADING';
export const GET_FIGHTERS_ERROR = 'GET_FIGHTERS_ERROR';
export const REFRESH_FIGHTER_LIST_LOADING = 'REFRESH_FIGHTER_LIST_LOADING';
export const REFRESH_FIGHTER_LIST_SUCCESS = 'REFRESH_FIGHTER_LIST_SUCCESS';
export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const SET_SHOWN_FIGHTERS = 'SET_SHOWN_FIGHTERS';